dbfound:
  system:
    model-modify-check: true
  web:
    base-path: /
  datasource:
    db0:
      url: jdbc:mysql://smysql01.sz.gomo.com:3306/dbfound?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username:
      password:
      dialect: MySqlDialect

spring:
  profiles:
    active: dev
  application:
    name: dbfound-springboot-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE

server:
  servlet:
    jsp:
      init-parameters:
        development: true
