dbfound:
  system:
    model-modify-check: true
  web:
    base-path: ${@contextPath}
  datasource:
    db0:
      url: jdbc:mysql://127.0.0.1/dbfound?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: dbfound
      password: dbfound
      dialect: MySqlDialect

spring:
  profiles:
    active: dev
  application:
    name: dbfound-springboot-demo
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
server:
  servlet:
    jsp:
      init-parameters:
        development: true
